services:
  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379/0
      PYTHONPATH: /app
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  test:
    build: .
    command: poetry run pytest --asyncio-mode=auto --cov=app --cov-report=html tests/ -v
    depends_on:
      - api
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379/0
      PYTHONPATH: /app
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mongo_data:
